# Generated by Django 2.1 on 2019-04-10 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('enunciado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=250)),
                ('id_questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prova.Questao')),
            ],
        ),
        migrations.AddField(
            model_name='questao',
            name='resposta_correta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='prova.Resposta'),
        ),
    ]
